theme: jekyll-theme-chirpy

lang: en

timezone:

title: Chirpy
tagline: A text-focused Jekyll theme
description: >-
  A minimal, responsive and feature-rich Jekyll theme for technical writing.

url: ""

github:
  username: github_username

social:
  name: Luka
  email: luka.chia

baseurl: ""

toc: true

paginate: 10
