theme: jekyll-theme-chirpy

lang: zh-CN

timezone: Asia/Shanghai

title: Luka Chia

tagline: Cloud · Infrastructure · Architecture · Security

description: >-
  Technical notes and engineering experience in Cloud,
  Infrastructure, Networking, Security and Architecture.

url: "https://luka-chia.github.io"

github:
  username: luka-chia

social:
  name: Luka Chia

baseurl: ""

toc: true

paginate: 10
