theme: jekyll-theme-chirpy

lang: zh-CN

timezone: Asia/Shanghai

title: Luka Chia

tagline: Cloud · Infrastructure · Architecture · Network · Security

description: >-
  Technical notes and engineering experience in Cloud,
  Infrastructure, Networking, Security and Architecture.

url: "https://luka-chia.github.io"

github:
  username: luka-chia

social:
  name: Luka Chia
  links:
    - https://github.com/luka-chia

baseurl: ""

toc: true

paginate: 10

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/

  - scope:
      path: _drafts
    values:
      comments: false

  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/
